import store from "@/redux/store";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import App from "./App";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next-Auth Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          {children}
        </App>
      </body>
    </html>
  );
}
